"""initial_migration

Revision ID: 6a3e04989666
Revises: 
Create Date: 2025-11-12 22:43:10.924309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3e04989666'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_email'), 'authors', ['email'], unique=False)
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_index(op.f('ix_authors_user_id'), 'authors', ['user_id'], unique=False)
    op.create_table('photo_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hothashes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_collections_id'), 'photo_collections', ['id'], unique=False)
    op.create_index(op.f('ix_photo_collections_user_id'), 'photo_collections', ['user_id'], unique=False)
    op.create_table('photo_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stack_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_stacks_id'), 'photo_stacks', ['id'], unique=False)
    op.create_index(op.f('ix_photo_stacks_user_id'), 'photo_stacks', ['user_id'], unique=False)
    op.create_table('phototext_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('cover_image_hash', sa.String(length=64), nullable=True),
    sa.Column('cover_image_alt', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("document_type IN ('general', 'album', 'slideshow')", name='valid_document_type'),
    sa.CheckConstraint("visibility IN ('private', 'space', 'authenticated', 'public')", name='valid_document_visibility'),
    sa.CheckConstraint('(cover_image_hash IS NULL AND cover_image_alt IS NULL) OR (cover_image_hash IS NOT NULL AND cover_image_alt IS NOT NULL)', name='valid_cover_image'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phototext_documents_document_type'), 'phototext_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_phototext_documents_id'), 'phototext_documents', ['id'], unique=False)
    op.create_index(op.f('ix_phototext_documents_is_published'), 'phototext_documents', ['is_published'], unique=False)
    op.create_index(op.f('ix_phototext_documents_user_id'), 'phototext_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_phototext_documents_visibility'), 'phototext_documents', ['visibility'], unique=False)
    op.create_table('saved_photo_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('search_criteria', sa.JSON(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_photo_searches_user_id'), 'saved_photo_searches', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_tag_unique', 'tags', ['user_id', 'name'], unique=True)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('import_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('default_author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_sessions_default_author_id'), 'import_sessions', ['default_author_id'], unique=False)
    op.create_index(op.f('ix_import_sessions_id'), 'import_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_import_sessions_user_id'), 'import_sessions', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hothash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotpreview', sa.LargeBinary(), nullable=False),
    sa.Column('exif_dict', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('import_session_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.Column('coldpreview_path', sa.String(length=255), nullable=True),
    sa.Column('timeloc_correction', sa.JSON(), nullable=True),
    sa.Column('view_correction', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("visibility IN ('private', 'space', 'authenticated', 'public')", name='valid_photo_visibility'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['import_session_id'], ['import_sessions.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['photo_stacks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_author_id'), 'photos', ['author_id'], unique=False)
    op.create_index(op.f('ix_photos_category'), 'photos', ['category'], unique=False)
    op.create_index(op.f('ix_photos_hothash'), 'photos', ['hothash'], unique=True)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_index(op.f('ix_photos_import_session_id'), 'photos', ['import_session_id'], unique=False)
    op.create_index(op.f('ix_photos_stack_id'), 'photos', ['stack_id'], unique=False)
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_index(op.f('ix_photos_visibility'), 'photos', ['visibility'], unique=False)
    op.create_table('image_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('imported_time', sa.DateTime(), nullable=True),
    sa.Column('imported_info', sa.JSON(), nullable=True),
    sa.Column('local_storage_info', sa.JSON(), nullable=True),
    sa.Column('cloud_storage_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_files_id'), 'image_files', ['id'], unique=False)
    op.create_index(op.f('ix_image_files_photo_id'), 'image_files', ['photo_id'], unique=False)
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'tag_id')
    )
    op.create_index('idx_photo_tags', 'photo_tags', ['photo_id', 'tag_id'], unique=False)
    op.create_index('idx_tag_photos', 'photo_tags', ['tag_id', 'photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tag_photos', table_name='photo_tags')
    op.drop_index('idx_photo_tags', table_name='photo_tags')
    op.drop_table('photo_tags')
    op.drop_index(op.f('ix_image_files_photo_id'), table_name='image_files')
    op.drop_index(op.f('ix_image_files_id'), table_name='image_files')
    op.drop_table('image_files')
    op.drop_index(op.f('ix_photos_visibility'), table_name='photos')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_stack_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_import_session_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_hothash'), table_name='photos')
    op.drop_index(op.f('ix_photos_category'), table_name='photos')
    op.drop_index(op.f('ix_photos_author_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_import_sessions_user_id'), table_name='import_sessions')
    op.drop_index(op.f('ix_import_sessions_id'), table_name='import_sessions')
    op.drop_index(op.f('ix_import_sessions_default_author_id'), table_name='import_sessions')
    op.drop_table('import_sessions')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index('idx_user_tag_unique', table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_saved_photo_searches_user_id'), table_name='saved_photo_searches')
    op.drop_table('saved_photo_searches')
    op.drop_index(op.f('ix_phototext_documents_visibility'), table_name='phototext_documents')
    op.drop_index(op.f('ix_phototext_documents_user_id'), table_name='phototext_documents')
    op.drop_index(op.f('ix_phototext_documents_is_published'), table_name='phototext_documents')
    op.drop_index(op.f('ix_phototext_documents_id'), table_name='phototext_documents')
    op.drop_index(op.f('ix_phototext_documents_document_type'), table_name='phototext_documents')
    op.drop_table('phototext_documents')
    op.drop_index(op.f('ix_photo_stacks_user_id'), table_name='photo_stacks')
    op.drop_index(op.f('ix_photo_stacks_id'), table_name='photo_stacks')
    op.drop_table('photo_stacks')
    op.drop_index(op.f('ix_photo_collections_user_id'), table_name='photo_collections')
    op.drop_index(op.f('ix_photo_collections_id'), table_name='photo_collections')
    op.drop_table('photo_collections')
    op.drop_index(op.f('ix_authors_user_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_email'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
