"""
Example: Using Real PhotoEgg Fixtures in Tests

This file demonstrates how to use pre-generated PhotoEgg fixtures
from imalink-core instead of creating mock objects.
"""

import pytest
from tests.fixtures.real_photo_eggs import (
    load_photoegg, 
    BASIC, 
    LANDSCAPE, 
    TINY,
    FUJI_WITH_COLDPREVIEW
)


class TestPhotoCreationWithRealPhotoEggs:
    """
    Example tests showing how to use real PhotoEgg fixtures.
    
    These PhotoEggs are REAL - generated by imalink-core from actual test images,
    with real hothashes, base64 previews, and metadata.
    """
    
    def test_create_photo_from_basic_photoegg(self, client, auth_headers):
        """Create photo using basic PhotoEgg fixture"""
        
        # Load real PhotoEgg from fixture
        photoegg = load_photoegg(BASIC)
        
        # Verify it has expected structure
        assert "hothash" in photoegg
        assert "hotpreview_base64" in photoegg
        assert "primary_filename" in photoegg
        
        # Create photo via API
        response = client.post(
            "/api/v1/photos/new-photo",
            json=photoegg,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Photo should have same hothash
        assert photo["hothash"] == photoegg["hothash"]
        assert photo["width"] == photoegg["width"]
        assert photo["height"] == photoegg["height"]
    
    
    def test_create_landscape_photo(self, client, auth_headers):
        """Create landscape photo using real fixture"""
        
        photoegg = load_photoegg(LANDSCAPE)
        
        response = client.post(
            "/api/v1/photos/new-photo",
            json=photoegg,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Landscape photos have width > height
        assert photo["width"] > photo["height"]
    
    
    def test_create_photo_with_coldpreview(self, client, auth_headers):
        """Create photo with both hot and cold previews"""
        
        photoegg = load_photoegg(FUJI_WITH_COLDPREVIEW)
        
        # This PhotoEgg should have coldpreview
        assert photoegg.get("coldpreview_base64") is not None
        
        response = client.post(
            "/api/v1/photos/new-photo",
            json=photoegg,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Backend should store coldpreview info
        assert photo["hothash"] == photoegg["hothash"]
    
    
    def test_create_tiny_image(self, client, auth_headers):
        """Create very small image (100x100 pixels)"""
        
        photoegg = load_photoegg(TINY)
        
        response = client.post(
            "/api/v1/photos/new-photo",
            json=photoegg,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Small image dimensions should be preserved
        assert photo["width"] == photoegg["width"]
        assert photo["height"] == photoegg["height"]
    
    
    def test_duplicate_photoegg_rejected(self, client, auth_headers):
        """Uploading same PhotoEgg twice should detect duplicate"""
        
        photoegg = load_photoegg(BASIC)
        
        # First upload succeeds
        response1 = client.post(
            "/api/v1/photos/new-photo",
            json=photoegg,
            headers=auth_headers
        )
        assert response1.status_code == 201
        
        # Second upload of SAME hothash should fail or return existing
        response2 = client.post(
            "/api/v1/photos/new-photo",
            json=photoegg,
            headers=auth_headers
        )
        
        # Should either reject (409) or return existing photo
        assert response2.status_code in [409, 200, 201]
        
        if response2.status_code == 200:
            # If returning existing, hothash should match
            assert response2.json()["hothash"] == photoegg["hothash"]


class TestCompareWithMockData:
    """
    Example showing difference between mock data and real PhotoEggs.
    
    Real PhotoEggs are better because:
    - Actual hothashes (64-char SHA256)
    - Real base64-encoded JPEG previews
    - Realistic dimensions and metadata
    - Test what frontend ACTUALLY sends
    """
    
    def test_mock_photoegg_old_way(self, client, auth_headers):
        """OLD WAY: Creating mock PhotoEgg manually"""
        
        mock_photoegg = {
            "hothash": "a" * 64,  # Fake hash
            "hotpreview_base64": "fake_base64",  # Not real JPEG
            "primary_filename": "test.jpg",
            "width": 800,
            "height": 600,
            # ... many other fields to mock
        }
        
        # This might work in tests, but doesn't match reality
        # Real frontend sends actual base64 JPEGs, not "fake_base64"
        pass
    
    
    def test_real_photoegg_new_way(self, client, auth_headers):
        """NEW WAY: Using real PhotoEgg from imalink-core"""
        
        photoegg = load_photoegg(BASIC)
        
        # Real hothash (SHA256 of actual hotpreview)
        assert len(photoegg["hothash"]) == 64
        assert photoegg["hothash"].isalnum()
        
        # Real base64-encoded JPEG
        assert photoegg["hotpreview_base64"].startswith("/9j/")  # JPEG header
        
        # Real dimensions from actual image
        assert photoegg["width"] > 0
        assert photoegg["height"] > 0
        
        # This matches what frontend ACTUALLY sends!


# Usage in conftest.py fixtures
@pytest.fixture
def sample_photoegg():
    """Fixture providing a real PhotoEgg for tests"""
    return load_photoegg(BASIC)


@pytest.fixture
def landscape_photoegg():
    """Fixture providing a landscape PhotoEgg"""
    return load_photoegg(LANDSCAPE)


# Usage in parametrized tests
@pytest.mark.parametrize("fixture_name", [
    BASIC,
    LANDSCAPE,
    TINY,
])
def test_create_photos_parametrized(fixture_name, client, auth_headers):
    """Create photos using different PhotoEgg fixtures"""
    
    photoegg = load_photoegg(fixture_name)
    
    response = client.post(
        "/api/v1/photos/new-photo",
        json=photoegg,
        headers=auth_headers
    )
    
    assert response.status_code == 201
    photo = response.json()
    assert photo["hothash"] == photoegg["hothash"]
