"""
Example: Using Real PhotoCreateSchema Fixtures in Tests

This file demonstrates how to use pre-generated PhotoCreateSchema fixtures
from imalink-core instead of creating mock objects.
"""

import pytest
from tests.fixtures.real_photo_create_schemas import (
    load_photo_create_schema, 
    BASIC, 
    LANDSCAPE, 
    TINY,
    FUJI_WITH_COLDPREVIEW
)


class TestPhotoCreationWithRealPhotoCreateSchemas:
    """
    Example tests showing how to use real PhotoCreateSchema fixtures.
    
    These PhotoCreateSchemas are REAL - generated by imalink-core from actual test images,
    with real hothashes, base64 previews, and metadata.
    """
    
    def test_create_photo_from_basic_photo_create_schema(self, client, auth_headers, input_channel):
        """Basic PhotoCreateSchema → Photo creation flow"""
        
        photo_create_data = load_photo_create_schema(
            BASIC,
            rating=0,
            visibility="private",
            input_channel_id=input_channel.id
        )
        
        # Verify it has expected NEW structure
        assert "hothash" in photo_create_data
        assert "hotpreview_base64" in photo_create_data
        assert "image_file_list" in photo_create_data  # NEW: replaces primary_filename
        assert "exif_dict" in photo_create_data        # NEW: camera data here
        
        # PhotoCreateRequest format (simplified - PhotoCreateSchema contains all fields)
        request_body = {
            "photo_create_schema": photo_create_data,
            "tags": []
        }
        
        # Create photo via PhotoCreateSchema API
        response = client.post(
            "/api/v1/photos/create",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Photo should have same hothash
        assert photo["hothash"] == photo_create_data["hothash"]
    
    
    def test_create_landscape_photo(self, client, auth_headers, input_channel):
        """Create photo from landscape orientation PhotoCreateSchema"""
        
        photo_create_data = load_photo_create_schema(
            LANDSCAPE,
            rating=4,
            visibility="public",
            input_channel_id=input_channel.id
        )
        
        request_body = {
            "photo_create_schema": photo_create_data,
            "tags": ["landscape", "nature"]
        }
        
        response = client.post(
            "/api/v1/photos/create",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Verify landscape dimensions
        assert photo["width"] == photo_create_data["width"]
        assert photo["height"] == photo_create_data["height"]
        assert photo["rating"] == 4
        assert photo["visibility"] == "public"
    
    
    def test_create_photo_with_coldpreview(self, client, auth_headers, input_channel):
        """Create photo that includes coldpreview"""
        
        photo_create_data = load_photo_create_schema(
            FUJI_WITH_COLDPREVIEW,
            rating=5,
            visibility="private",
            input_channel_id=input_channel.id
        )
        
        # This PhotoCreateSchema has coldpreview
        assert photo_create_data["coldpreview_base64"] is not None
        
        request_body = {
            "photo_create_schema": photo_create_data,
            "tags": []
        }
        
        response = client.post(
            "/api/v1/photos/create",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Photo created successfully
        assert photo["hothash"] == photo_create_data["hothash"]
        assert photo["rating"] == 5
    
    
    def test_create_tiny_image(self, client, auth_headers, input_channel):
        """Create photo from tiny test image"""
        
        photo_create_data = load_photo_create_schema(TINY)
        
        request_body = {
            "photo_create_schema": photo_create_data,
            "rating": 0,
            "visibility": "private",
            "tags": [],
            "import_session_id": input_channel.id
        }
        
        response = client.post(
            "/api/v1/photos/create",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Small image dimensions should be preserved
        assert photo["width"] == photo_create_data["width"]
        assert photo["height"] == photo_create_data["height"]
    
    
    def test_duplicate_photo_create_schema_rejected(self, client, auth_headers, input_channel):
        """Uploading same PhotoCreateSchema twice should detect duplicate"""
        
        photo_create_data = load_photo_create_schema(BASIC)
        
        request_body = {
            "photo_create_schema": photo_create_data,
            "rating": 0,
            "visibility": "private",
            "tags": [],
            "import_session_id": input_channel.id
        }
        
        # First upload succeeds
        response1 = client.post(
            "/api/v1/photos/create",
            json=request_body,
            headers=auth_headers
        )
        assert response1.status_code == 201
        photo1 = response1.json()
        assert photo1["is_duplicate"] == False
        
        # Second upload of SAME hothash returns existing with is_duplicate=True
        response2 = client.post(
            "/api/v1/photos/create",
            json=request_body,
            headers=auth_headers
        )
        
        # Should return 201 with is_duplicate flag
        assert response2.status_code == 201
        photo2 = response2.json()
        assert photo2["is_duplicate"] == True
        assert photo2["hothash"] == photo_create_data["hothash"]
        assert photo2["id"] == photo1["id"]  # Same photo returned


class TestCompareWithMockData:
    """
    Example showing difference between mock data and real PhotoCreateSchemas.
    
    Real PhotoCreateSchemas are better because:
    - Actual hothashes (64-char SHA256)
    - Real base64-encoded JPEG previews
    - Realistic dimensions and metadata
    - Test what frontend ACTUALLY sends
    """
    
    def test_mock_photo_create_schema_old_way(self, client, auth_headers):
        """OLD WAY: Creating mock PhotoCreateSchema manually"""
        
        mock_photo_create_schema = {
            "hothash": "a" * 64,  # Fake hash
            "hotpreview_base64": "fake_base64",  # Not real JPEG
            "primary_filename": "test.jpg",
            "width": 800,
            "height": 600,
            # ... many other fields to mock
        }
        
        # This might work in tests, but doesn't match reality
        # Real frontend sends actual base64 JPEGs, not "fake_base64"
        pass
    
    
    def test_real_photo_create_schema_new_way(self, client, auth_headers):
        """NEW WAY: Using real PhotoCreateSchema from imalink-core"""
        
        photo_create_schema = load_photo_create_schema(BASIC)
        
        # Real hothash (SHA256 of actual hotpreview)
        assert len(photo_create_schema["hothash"]) == 64
        assert photo_create_schema["hothash"].isalnum()
        
        # Real base64-encoded JPEG
        assert photo_create_schema["hotpreview_base64"].startswith("/9j/")  # JPEG header
        
        # Real dimensions from actual image
        assert photo_create_schema["width"] > 0
        assert photo_create_schema["height"] > 0
        
        # This matches what frontend ACTUALLY sends!


# Usage in conftest.py fixtures
@pytest.fixture
def sample_photo_create_schema():
    """Fixture providing a real PhotoCreateSchema for tests"""
    return load_photo_create_schema(BASIC)


@pytest.fixture
def landscape_photo_create_schema():
    """Fixture providing a landscape PhotoCreateSchema"""
    return load_photo_create_schema(LANDSCAPE)


# Usage in parametrized tests
@pytest.mark.parametrize("fixture_name", [
    BASIC,
    LANDSCAPE,
    TINY,
])
def test_create_photos_parametrized(fixture_name, client, auth_headers, input_channel):
    """Create photos using different PhotoCreateSchema fixtures"""
    
    photo_create_data = load_photo_create_schema(fixture_name)
    
    request_body = {
        "photo_create_schema": photo_create_data,
        "rating": 0,
        "visibility": "private",
        "tags": [],
        "import_session_id": input_channel.id
    }
    
    response = client.post(
        "/api/v1/photos/create",
        json=request_body,
        headers=auth_headers
    )
    
    assert response.status_code == 201
    photo = response.json()
    assert photo["hothash"] == photo_create_data["hothash"]
