"""
Example: Using Real PhotoEgg Fixtures in Tests

This file demonstrates how to use pre-generated PhotoEgg fixtures
from imalink-core instead of creating mock objects.
"""

import pytest
from tests.fixtures.real_photo_eggs import (
    load_photoegg, 
    BASIC, 
    LANDSCAPE, 
    TINY,
    FUJI_WITH_COLDPREVIEW
)


class TestPhotoCreationWithRealPhotoEggs:
    """
    Example tests showing how to use real PhotoEgg fixtures.
    
    These PhotoEggs are REAL - generated by imalink-core from actual test images,
    with real hothashes, base64 previews, and metadata.
    """
    
    def test_create_photo_from_basic_photoegg(self, client, auth_headers, import_session):
        """Basic PhotoEgg → Photo creation flow"""
        
        photoegg_data = load_photoegg(BASIC)
        
        # Verify it has expected structure
        assert "hothash" in photoegg_data
        assert "hotpreview_base64" in photoegg_data
        assert "primary_filename" in photoegg_data
        
        # Wrap PhotoEgg in PhotoEggRequest format
        request_body = {
            "photo_egg": photoegg_data,
            "rating": 0,
            "visibility": "private",
            "tags": [],
            "import_session_id": import_session.id
        }
        
        # Create photo via PhotoEgg API
        response = client.post(
            "/api/v1/photos/photoegg",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Photo should have same hothash
        assert photo["hothash"] == photoegg_data["hothash"]
    
    
    def test_create_landscape_photo(self, client, auth_headers, import_session):
        """Create photo from landscape orientation PhotoEgg"""
        
        photoegg_data = load_photoegg(LANDSCAPE)
        
        request_body = {
            "photo_egg": photoegg_data,
            "rating": 4,
            "visibility": "public",
            "tags": ["landscape", "nature"],
            "import_session_id": import_session.id
        }
        
        response = client.post(
            "/api/v1/photos/photoegg",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Verify landscape dimensions
        assert photo["width"] == photoegg_data["width"]
        assert photo["height"] == photoegg_data["height"]
        assert photo["rating"] == 4
        assert photo["visibility"] == "public"
    
    
    def test_create_photo_with_coldpreview(self, client, auth_headers, import_session):
        """Create photo that includes coldpreview"""
        
        photoegg_data = load_photoegg(FUJI_WITH_COLDPREVIEW)
        
        # This PhotoEgg has coldpreview
        assert photoegg_data["coldpreview_base64"] is not None
        
        request_body = {
            "photo_egg": photoegg_data,
            "rating": 5,
            "visibility": "private",
            "tags": [],
            "import_session_id": import_session.id
        }
        
        response = client.post(
            "/api/v1/photos/photoegg",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Photo created successfully
        assert photo["hothash"] == photoegg_data["hothash"]
        assert photo["rating"] == 5
    
    
    def test_create_tiny_image(self, client, auth_headers, import_session):
        """Create photo from tiny test image"""
        
        photoegg_data = load_photoegg(TINY)
        
        request_body = {
            "photo_egg": photoegg_data,
            "rating": 0,
            "visibility": "private",
            "tags": [],
            "import_session_id": import_session.id
        }
        
        response = client.post(
            "/api/v1/photos/photoegg",
            json=request_body,
            headers=auth_headers
        )
        
        assert response.status_code == 201
        photo = response.json()
        
        # Small image dimensions should be preserved
        assert photo["width"] == photoegg_data["width"]
        assert photo["height"] == photoegg_data["height"]
    
    
    def test_duplicate_photoegg_rejected(self, client, auth_headers, import_session):
        """Uploading same PhotoEgg twice should detect duplicate"""
        
        photoegg_data = load_photoegg(BASIC)
        
        request_body = {
            "photo_egg": photoegg_data,
            "rating": 0,
            "visibility": "private",
            "tags": [],
            "import_session_id": import_session.id
        }
        
        # First upload succeeds
        response1 = client.post(
            "/api/v1/photos/photoegg",
            json=request_body,
            headers=auth_headers
        )
        assert response1.status_code == 201
        photo1 = response1.json()
        assert photo1["is_duplicate"] == False
        
        # Second upload of SAME hothash returns existing with is_duplicate=True
        response2 = client.post(
            "/api/v1/photos/photoegg",
            json=request_body,
            headers=auth_headers
        )
        
        # Should return 201 with is_duplicate flag
        assert response2.status_code == 201
        photo2 = response2.json()
        assert photo2["is_duplicate"] == True
        assert photo2["hothash"] == photoegg_data["hothash"]
        assert photo2["id"] == photo1["id"]  # Same photo returned


class TestCompareWithMockData:
    """
    Example showing difference between mock data and real PhotoEggs.
    
    Real PhotoEggs are better because:
    - Actual hothashes (64-char SHA256)
    - Real base64-encoded JPEG previews
    - Realistic dimensions and metadata
    - Test what frontend ACTUALLY sends
    """
    
    def test_mock_photoegg_old_way(self, client, auth_headers):
        """OLD WAY: Creating mock PhotoEgg manually"""
        
        mock_photoegg = {
            "hothash": "a" * 64,  # Fake hash
            "hotpreview_base64": "fake_base64",  # Not real JPEG
            "primary_filename": "test.jpg",
            "width": 800,
            "height": 600,
            # ... many other fields to mock
        }
        
        # This might work in tests, but doesn't match reality
        # Real frontend sends actual base64 JPEGs, not "fake_base64"
        pass
    
    
    def test_real_photoegg_new_way(self, client, auth_headers):
        """NEW WAY: Using real PhotoEgg from imalink-core"""
        
        photoegg = load_photoegg(BASIC)
        
        # Real hothash (SHA256 of actual hotpreview)
        assert len(photoegg["hothash"]) == 64
        assert photoegg["hothash"].isalnum()
        
        # Real base64-encoded JPEG
        assert photoegg["hotpreview_base64"].startswith("/9j/")  # JPEG header
        
        # Real dimensions from actual image
        assert photoegg["width"] > 0
        assert photoegg["height"] > 0
        
        # This matches what frontend ACTUALLY sends!


# Usage in conftest.py fixtures
@pytest.fixture
def sample_photoegg():
    """Fixture providing a real PhotoEgg for tests"""
    return load_photoegg(BASIC)


@pytest.fixture
def landscape_photoegg():
    """Fixture providing a landscape PhotoEgg"""
    return load_photoegg(LANDSCAPE)


# Usage in parametrized tests
@pytest.mark.parametrize("fixture_name", [
    BASIC,
    LANDSCAPE,
    TINY,
])
def test_create_photos_parametrized(fixture_name, client, auth_headers, import_session):
    """Create photos using different PhotoEgg fixtures"""
    
    photoegg_data = load_photoegg(fixture_name)
    
    request_body = {
        "photo_egg": photoegg_data,
        "rating": 0,
        "visibility": "private",
        "tags": [],
        "import_session_id": import_session.id
    }
    
    response = client.post(
        "/api/v1/photos/photoegg",
        json=request_body,
        headers=auth_headers
    )
    
    assert response.status_code == 201
    photo = response.json()
    assert photo["hothash"] == photoegg_data["hothash"]
