"""
PhotoCreateSchema - Local definition (will be synced to imalink-schemas when stable)

PhotoCreateSchema structure (matches MY_OVERVIEW.md):
- hothash, hotpreview_base64, width, height
- exif_dict: ALL EXIF metadata (camera_make, iso, etc.)
- taken_at, gps_latitude, gps_longitude (indexed copies for queries)
- rating, category, visibility (user organization - set by frontend)
- image_file_list: list of ImageFileCreateSchema (JPEG + RAW companions)

IMPORTANT: user_id is NOT in PhotoCreateSchema - it's set by backend from JWT token!
"""
from typing import Optional, Any
from datetime import datetime
from pydantic import BaseModel, Field


class ImageFileCreateSchema(BaseModel):
    """Schema for source image file (JPEG, RAW, etc.)"""
    filename: str = Field(..., description="Original filename")
    file_size: int = Field(default=0, ge=0, description="File size in bytes")
    imported_time: Optional[datetime] = Field(None, description="When file was imported")
    imported_info: Optional[dict[str, Any]] = Field(None, description="Import metadata (JSON)")
    local_storage_info: Optional[dict[str, Any]] = Field(None, description="Local storage metadata")
    cloud_storage_info: Optional[dict[str, Any]] = Field(None, description="Cloud storage metadata")


class PhotoCreateSchema(BaseModel):
    """
    Schema for creating a Photo (generated by imalink-core, enhanced by frontend).
    
    Created by imalink-core from image file(s), then frontend adds user organization fields.
    Backend adds user_id from JWT token (NOT included in this schema).
    
    Key principles:
    - hothash is unique identifier (SHA256 of hotpreview)
    - exif_dict contains ALL EXIF metadata (flexible JSON)
    - Only taken_at, gps_latitude, gps_longitude copied to root for DB indexing
    - image_file_list contains one or more source files (JPEG + RAW companions)
    """
    
    # Identity - created by imalink-core
    hothash: str = Field(..., description="SHA256 hash of hotpreview (unique ID)")
    hotpreview_base64: str = Field(..., description="Base64 encoded JPEG preview (~200px)")
    
    # Complete EXIF metadata (readonly DNA)
    exif_dict: Optional[dict[str, Any]] = Field(
        None,
        description="Complete EXIF data (camera_make, iso, etc. - flexible schema)"
    )
    
    # Dimensions
    width: int = Field(..., description="Image width in pixels")
    height: int = Field(..., description="Image height in pixels")
    
    # Time & Location (indexed copies from exif_dict)
    taken_at: Optional[datetime] = Field(
        None,
        description="When photo was taken (for timeline queries)"
    )
    gps_latitude: Optional[float] = Field(
        None,
        description="GPS latitude (for map queries)"
    )
    gps_longitude: Optional[float] = Field(
        None,
        description="GPS longitude (for map queries)"
    )
    
    # User organization (set by frontend)
    rating: int = Field(default=0, ge=0, le=5, description="Star rating (0-5)")
    category: Optional[str] = Field(
        default=None,
        description="Category type (photo, screenshot, video, etc.)"
    )
    visibility: str = Field(
        default="private",
        description="Visibility level (private, space, authenticated, public)"
    )
    import_session_id: Optional[int] = Field(
        None,
        description="Import batch this photo belongs to"
    )
    author_id: Optional[int] = Field(
        None,
        description="Photographer/creator ID"
    )
    stack_id: Optional[int] = Field(
        None,
        description="Photo stack ID (for related images)"
    )
    
    # Optional larger preview
    coldpreview_base64: Optional[str] = Field(
        None,
        description="Base64 encoded larger JPEG preview (optional)"
    )
    
    # Corrections (user-editable overrides)
    timeloc_correction: Optional[dict[str, Any]] = Field(
        None,
        description="Time/location corrections (timezone fix, GPS override, etc.)"
    )
    view_correction: Optional[dict[str, Any]] = Field(
        None,
        description="Visual adjustments (rotation, crop hints for frontend)"
    )
    
    # Source files
    image_file_list: list[ImageFileCreateSchema] = Field(
        default_factory=list,
        description="List of source image files (JPEG + RAW companions)"
    )


class PhotoUpdateSchema(BaseModel):
    """Schema for updating a Photo"""
    rating: Optional[int] = Field(None, ge=0, le=5)
    category: Optional[str] = None
    visibility: Optional[str] = None
    author_id: Optional[int] = None
    stack_id: Optional[int] = None
    timeloc_correction: Optional[dict[str, Any]] = None
    view_correction: Optional[dict[str, Any]] = None


class PhotoResponse(BaseModel):
    """Base response schema for Photo"""
    id: int
    hothash: str
    width: int
    height: int
    rating: int
    visibility: str
    taken_at: Optional[datetime] = None
    created_at: datetime
    user_id: int  # Included in response (for ownership display)


class PhotoCreateRequest(BaseModel):
    """
    Request wrapper for creating Photo via API.
    
    PhotoCreateSchema contains image data from imalink-core + frontend organization fields.
    This wrapper adds tags (handled via separate PhotoTag relationship).
    
    Backend will add user_id from JWT token (not in PhotoCreateSchema).
    """
    photo_create_schema: PhotoCreateSchema
    tags: list[str] = Field(default_factory=list, description="Tag names to associate")


class PhotoCreateResponse(PhotoResponse):
    """
    Response after creating Photo.
    
    Extends PhotoResponse with creation-specific fields.
    """
    created_at: datetime = Field(..., description="When photo was created in database")
    is_duplicate: bool = Field(default=False, description="True if hothash already existed")
    
    class Config:
        from_attributes = True


# Re-export for convenience
__all__ = [
    "PhotoCreateSchema",
    "ImageFileCreateSchema",
    "PhotoUpdateSchema",
    "PhotoResponse",
    "PhotoCreateRequest",
    "PhotoCreateResponse",
]
