"""
Real PhotoEgg Test Fixtures

Utilities for loading pre-generated PhotoEgg JSON files created by imalink-core.

These are REAL PhotoEggs - not mocks - generated by processing actual test images
through imalink-core service.

Usage:
    from tests.fixtures.real_photo_eggs import load_photoegg, list_available
    
    # Load a specific PhotoEgg
    egg = load_photoegg("basic")
    
    # Use in API tests
    response = client.post("/api/v1/photos/new-photo", json=egg)
    
    # List all available fixtures
    available = list_available()
"""

import json
from pathlib import Path
from typing import Dict, Any, List


FIXTURES_DIR = Path(__file__).parent / "photo_eggs"


def load_photoegg(name: str) -> Dict[str, Any]:
    """
    Load a real PhotoEgg fixture by name.
    
    These are actual PhotoEggs generated by imalink-core from real test images,
    matching the exact JSON structure the backend receives from the frontend.
    
    Args:
        name: Fixture name without .json extension (e.g., "basic", "gps")
        
    Returns:
        PhotoEgg dict matching imalink-core's output format
        
    Raises:
        FileNotFoundError: If fixture doesn't exist
        
    Examples:
        >>> egg = load_photoegg("basic")
        >>> egg["hothash"]  # Real SHA256 hash from imalink-core
        'abc123...'
        
        >>> egg_with_gps = load_photoegg("gps")
        >>> egg_with_gps["has_gps"]
        True
        >>> egg_with_gps["gps_latitude"]  # Real GPS from test image
        43.467448
    """
    fixture_path = FIXTURES_DIR / f"{name}.json"
    
    if not fixture_path.exists():
        available = list_available()
        if not available:
            raise FileNotFoundError(
                f"No PhotoEgg fixtures found in {FIXTURES_DIR}. "
                "Run: uv run python scripts/generate_photoegg_fixtures.py"
            )
        raise FileNotFoundError(
            f"PhotoEgg fixture '{name}' not found. "
            f"Available: {', '.join(available)}"
        )
    
    with open(fixture_path) as f:
        return json.load(f)


def load_photoegg_bytes(name: str) -> bytes:
    """
    Load PhotoEgg as JSON bytes (for direct HTTP requests).
    
    Args:
        name: Fixture name without .json extension
        
    Returns:
        JSON bytes ready for HTTP POST
        
    Examples:
        >>> data = load_photoegg_bytes("basic")
        >>> response = client.post("/api/v1/photos/new-photo", 
        ...                        data=data, 
        ...                        headers={"Content-Type": "application/json"})
    """
    photoegg = load_photoegg(name)
    return json.dumps(photoegg).encode("utf-8")


def list_available() -> List[str]:
    """
    List all available PhotoEgg fixtures.
    
    Returns:
        List of fixture names (without .json extension)
        
    Examples:
        >>> fixtures = list_available()
        >>> "basic" in fixtures
        True
        >>> "gps" in fixtures
        True
    """
    if not FIXTURES_DIR.exists():
        return []
    
    return sorted([
        f.stem for f in FIXTURES_DIR.glob("*.json")
    ])


def get_fixture_path(name: str) -> Path:
    """
    Get the file path for a PhotoEgg fixture.
    
    Args:
        name: Fixture name without .json extension
        
    Returns:
        Path to the fixture JSON file
        
    Examples:
        >>> path = get_fixture_path("basic")
        >>> path.exists()
        True
    """
    return FIXTURES_DIR / f"{name}.json"


def photoegg_exists(name: str) -> bool:
    """
    Check if a PhotoEgg fixture exists.
    
    Args:
        name: Fixture name without .json extension
        
    Returns:
        True if fixture exists, False otherwise
    """
    return get_fixture_path(name).exists()


# Convenience constants for common fixtures
# These match the names generated by scripts/generate_photoegg_fixtures.py
BASIC = "basic"
BASIC_WITH_COLDPREVIEW = "basic_with_coldpreview"
NO_EXIF = "no_exif"
GPS = "gps"
ROTATED = "rotated"
LANDSCAPE = "landscape"
LANDSCAPE_WITH_COLDPREVIEW = "landscape_with_coldpreview"
PNG = "png"
TINY = "tiny"
CANON = "canon"
FUJI = "fuji"
FUJI_WITH_COLDPREVIEW = "fuji_with_coldpreview"


__all__ = [
    "load_photoegg",
    "load_photoegg_bytes",
    "list_available",
    "get_fixture_path",
    "photoegg_exists",
    # Fixture name constants
    "BASIC",
    "BASIC_WITH_COLDPREVIEW",
    "NO_EXIF",
    "GPS",
    "ROTATED",
    "LANDSCAPE",
    "LANDSCAPE_WITH_COLDPREVIEW",
    "PNG",
    "TINY",
    "CANON",
    "FUJI",
    "FUJI_WITH_COLDPREVIEW",
]
