"""
Real PhotoCreateSchema Test Fixtures

Utilities for loading pre-generated PhotoCreateSchema JSON files created by imalink-core.

These are REAL PhotoCreateSchemas - not mocks - generated by processing actual test images
through imalink-core service.

Usage:
    from tests.fixtures.real_photo_create_schemas import load_photo_create_schema, list_available
    
    # Load a specific PhotoCreateSchema
    schema = load_photo_create_schema("basic")
    
    # Use in API tests
    response = client.post("/api/v1/photos/new-photo", json=egg)
    
    # List all available fixtures
    available = list_available()
"""

import json
from pathlib import Path
from typing import Dict, Any, List


FIXTURES_DIR = Path(__file__).parent / "photo_create_schemas"


def load_photo_create_schema(
    name: str,
    rating: int = 0,
    category: str | None = None,
    visibility: str = "private",
    import_session_id: int | None = None,
    author_id: int | None = None,
) -> Dict[str, Any]:
    """
    Load a real PhotoCreateSchema fixture by name.
    
    ⚠️ NOTE: Fixtures are from imalink-core v1 (old format).
    This function automatically adapts them to v2 structure.
    
    IMPORTANT: user_id is NOT included - backend sets it from JWT token.
    
    Args:
        name: Fixture name without .json extension (e.g., "basic", "gps")
        rating: Star rating 0-5 (default: 0)
        category: Photo category (default: None)
        visibility: Visibility level (default: "private")
        import_session_id: Import session ID (default: None)
        author_id: Author ID (default: None)
        
    Returns:
        PhotoCreateSchema dict (WITHOUT user_id - backend adds it)
        
    Raises:
        FileNotFoundError: If fixture doesn't exist
        
    Examples:
        >>> schema = load_photo_create_schema("basic", rating=4)
        >>> schema["hothash"]  # Real SHA256 hash
        'abc123...'
        >>> "user_id" in schema  # False - backend sets it
        False
    """
    from tests.fixtures.schema_adapter import adapt_old_photo_create_schema
    
    fixture_path = FIXTURES_DIR / f"{name}.json"
    
    if not fixture_path.exists():
        available = list_available()
        if not available:
            raise FileNotFoundError(
                f"No PhotoCreateSchema fixtures found in {FIXTURES_DIR}. "
                "Run: uv run python scripts/generate_photo_create_schema_fixtures.py"
            )
        raise FileNotFoundError(
            f"PhotoCreateSchema fixture '{name}' not found. "
            f"Available: {', '.join(available)}"
        )
    
    with open(fixture_path) as f:
        old_schema = json.load(f)
    
    # Adapt old format to new format (WITHOUT user_id)
    return adapt_old_photo_create_schema(
        old_schema,
        rating=rating,
        category=category,
        visibility=visibility,
        import_session_id=import_session_id,
        author_id=author_id,
    )


def load_photo_create_schema_bytes(name: str) -> bytes:
    """
    Load PhotoCreateSchema as JSON bytes (for direct HTTP requests).
    
    Args:
        name: Fixture name without .json extension
        
    Returns:
        JSON bytes ready for HTTP POST
        
    Examples:
        >>> data = load_photo_create_schema_bytes("basic")
        >>> response = client.post("/api/v1/photos/new-photo", 
        ...                        data=data, 
        ...                        headers={"Content-Type": "application/json"})
    """
    photo_create_schema = load_photo_create_schema(name)
    return json.dumps(photo_create_schema).encode("utf-8")


def list_available() -> List[str]:
    """
    List all available PhotoCreateSchema fixtures.
    
    Returns:
        List of fixture names (without .json extension)
        
    Examples:
        >>> fixtures = list_available()
        >>> "basic" in fixtures
        True
        >>> "gps" in fixtures
        True
    """
    if not FIXTURES_DIR.exists():
        return []
    
    return sorted([
        f.stem for f in FIXTURES_DIR.glob("*.json")
    ])


def get_fixture_path(name: str) -> Path:
    """
    Get the file path for a PhotoCreateSchema fixture.
    
    Args:
        name: Fixture name without .json extension
        
    Returns:
        Path to the fixture JSON file
        
    Examples:
        >>> path = get_fixture_path("basic")
        >>> path.exists()
        True
    """
    return FIXTURES_DIR / f"{name}.json"


def photo_create_schema_exists(name: str) -> bool:
    """
    Check if a PhotoCreateSchema fixture exists.
    
    Args:
        name: Fixture name without .json extension
        
    Returns:
        True if fixture exists, False otherwise
    """
    return get_fixture_path(name).exists()


# Convenience constants for common fixtures
# These match the names generated by scripts/generate_photo_create_schema_fixtures.py
BASIC = "basic"
BASIC_WITH_COLDPREVIEW = "basic_with_coldpreview"
NO_EXIF = "no_exif"
GPS = "gps"
ROTATED = "rotated"
LANDSCAPE = "landscape"
LANDSCAPE_WITH_COLDPREVIEW = "landscape_with_coldpreview"
PNG = "png"
TINY = "tiny"
CANON = "canon"
FUJI = "fuji"
FUJI_WITH_COLDPREVIEW = "fuji_with_coldpreview"


__all__ = [
    "load_photo_create_schema",
    "load_photo_create_schema_bytes",
    "list_available",
    "get_fixture_path",
    "photo_create_schema_exists",
    # Fixture name constants
    "BASIC",
    "BASIC_WITH_COLDPREVIEW",
    "NO_EXIF",
    "GPS",
    "ROTATED",
    "LANDSCAPE",
    "LANDSCAPE_WITH_COLDPREVIEW",
    "PNG",
    "TINY",
    "CANON",
    "FUJI",
    "FUJI_WITH_COLDPREVIEW",
]
